services:
  - type: web
    name: get-audit
    env: node
    buildCommand: |
      npm install
      PUPPETEER_CACHE_DIR=.cache npx puppeteer browsers install chrome
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_CACHE_DIR
        value: .cache
